// <auto-generated />
using System;
using HealthAxis.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthAxis.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615102119_Patient")]
    partial class Patient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthAxis.Api.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<int>("ConsultationFee")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Specialisation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            ConsultationFee = 500,
                            FullName = "Nandana",
                            IsActive = true,
                            Specialisation = "Cardiology",
                            YearsOfExperience = 3
                        },
                        new
                        {
                            DoctorId = 2,
                            ConsultationFee = 400,
                            FullName = "Arun Kumar",
                            IsActive = true,
                            Specialisation = "Dermatology",
                            YearsOfExperience = 5
                        },
                        new
                        {
                            DoctorId = 3,
                            ConsultationFee = 600,
                            FullName = "Meera Joseph",
                            IsActive = true,
                            Specialisation = "Pediatrics",
                            YearsOfExperience = 7
                        },
                        new
                        {
                            DoctorId = 4,
                            ConsultationFee = 550,
                            FullName = "Rahul Menon",
                            IsActive = true,
                            Specialisation = "Orthopedics",
                            YearsOfExperience = 4
                        },
                        new
                        {
                            DoctorId = 5,
                            ConsultationFee = 800,
                            FullName = "Anjali Nair",
                            IsActive = true,
                            Specialisation = "Neurology",
                            YearsOfExperience = 10
                        },
                        new
                        {
                            DoctorId = 6,
                            ConsultationFee = 300,
                            FullName = "Sandeep Varma",
                            IsActive = true,
                            Specialisation = "General Medicine",
                            YearsOfExperience = 2
                        });
                });

            modelBuilder.Entity("HealthAxis.Api.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsuranceID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
