// <auto-generated />
using System;
using HealthAxis.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthAxis.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615103015_HealthRecord")]
    partial class HealthRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthAxis.Api.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<string>("CancellationReason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("HealthAxis.Api.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<int>("ConsultationFee")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Specialisation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            ConsultationFee = 500,
                            FullName = "Nandana",
                            IsActive = true,
                            Specialisation = "Cardiology",
                            YearsOfExperience = 3
                        },
                        new
                        {
                            DoctorId = 2,
                            ConsultationFee = 400,
                            FullName = "Arun Kumar",
                            IsActive = true,
                            Specialisation = "Dermatology",
                            YearsOfExperience = 5
                        },
                        new
                        {
                            DoctorId = 3,
                            ConsultationFee = 600,
                            FullName = "Meera Joseph",
                            IsActive = true,
                            Specialisation = "Pediatrics",
                            YearsOfExperience = 7
                        },
                        new
                        {
                            DoctorId = 4,
                            ConsultationFee = 550,
                            FullName = "Rahul Menon",
                            IsActive = true,
                            Specialisation = "Orthopedics",
                            YearsOfExperience = 4
                        },
                        new
                        {
                            DoctorId = 5,
                            ConsultationFee = 800,
                            FullName = "Anjali Nair",
                            IsActive = true,
                            Specialisation = "Neurology",
                            YearsOfExperience = 10
                        },
                        new
                        {
                            DoctorId = 6,
                            ConsultationFee = 300,
                            FullName = "Sandeep Varma",
                            IsActive = true,
                            Specialisation = "General Medicine",
                            YearsOfExperience = 2
                        });
                });

            modelBuilder.Entity("HealthAxis.Api.Models.HealthRecord", b =>
                {
                    b.Property<int>("HealthRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthRecordId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Prescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("HealthRecordId");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("HealthRecords");
                });

            modelBuilder.Entity("HealthAxis.Api.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsuranceID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            DateOfBirth = new DateTime(1998, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nandana@example.com",
                            FullName = "Nandana Linson",
                            Gender = "Female",
                            InsuranceID = "INS1001",
                            IsActive = false,
                            PhoneNumber = "9876543210"
                        },
                        new
                        {
                            PatientId = 2,
                            DateOfBirth = new DateTime(1990, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "arjun@example.com",
                            FullName = "Arjun Menon",
                            Gender = "Male",
                            InsuranceID = "INS1002",
                            IsActive = false,
                            PhoneNumber = "9123456780"
                        },
                        new
                        {
                            PatientId = 3,
                            DateOfBirth = new DateTime(1985, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "meera@example.com",
                            FullName = "Meera Nair",
                            Gender = "Female",
                            InsuranceID = "INS1003",
                            IsActive = false,
                            PhoneNumber = "9988776655"
                        },
                        new
                        {
                            PatientId = 4,
                            DateOfBirth = new DateTime(2000, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rahul@example.com",
                            FullName = "Rahul Das",
                            Gender = "Male",
                            InsuranceID = "INS1004",
                            IsActive = false,
                            PhoneNumber = "9012345678"
                        },
                        new
                        {
                            PatientId = 5,
                            DateOfBirth = new DateTime(1995, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anjali@example.com",
                            FullName = "Anjali Varma",
                            Gender = "Female",
                            InsuranceID = "INS1005",
                            IsActive = false,
                            PhoneNumber = "9345678901"
                        });
                });

            modelBuilder.Entity("HealthAxis.Api.Models.Appointment", b =>
                {
                    b.HasOne("HealthAxis.Api.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthAxis.Api.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthAxis.Api.Models.HealthRecord", b =>
                {
                    b.HasOne("HealthAxis.Api.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthAxis.Api.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("HealthAxis.Api.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId");

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
